"""
    Just Shift It: Test-Time Prototype Shifting for Zero-Shot Generalization,
    https://arxiv.org/abs/2403.12952,
    https://github.com/elaine-sui/TPS
"""

import os
import pickle
import time

import torch

from ttabc.utils.tools import Summary, AverageMeter, ProgressMeter, accuracy, select_confident_samples, marginal_entropy, build_optimizer
from ttabc.model_selection.base_method import BaseMethod
from clip.prototype import wrap_prototype_shifter
from data.prompt_utils import get_classnames


class TPS(BaseMethod):
    """
    TPS: Test-Time Prototype Shifting
    
    Core Workflow:
    1. Load pre-computed class prototypes (generated by generate_prototypes.py)
    2. At test-time, learn small shift vectors to adjust prototypes
    3. Use marginal entropy loss with confidence-based sample selection
    4. Reset shift vectors for each test sample (independent adaptation)
    
    Differences from TPT:
    - TPT: Optimizes prompt tokens (requires text encoder forward pass)
    - TPS: Optimizes shift vectors (only vector addition, much faster)
    - TPS has ~100x fewer parameters and ~2-3x faster inference
    """
    
    def __init__(self, args):
        super().__init__(args)
        self.args = args

        self.classnames = get_classnames(args.test_sets)
        self.backbone = self.model
        self._setup_model(self.classnames, args.arch)

    def _prototype_suffix(self, prototype_type):
        suffix = ""
        if prototype_type in ["templates", "template"]:
            suffix = "_templates"
        elif prototype_type in ["gpt4"]:
            suffix = "_gpt4"
        elif prototype_type in ["gpt4_x_templates", "gpt4_templates", "gpt4x_templates"]:
            suffix = "_gpt4_templates"

        if prototype_type.endswith("_macro"):
            suffix += "_macro"
        if prototype_type.endswith("_raw"):
            suffix += "_raw"
        return suffix

    def _load_prototypes(self, classnames, arch, dataset):
        prototype_dir = getattr(self.args, 'prototype_dir', './prototypes')
        prototype_type = getattr(self.args, 'prototype_type', 'basic')
        suffix = self._prototype_suffix(prototype_type)

        filename = f"{dataset}_{arch.replace('/', '-')}{suffix}_prototypes.pkl"
        filepath = os.path.join(prototype_dir, filename)
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Prototype file not found: {filepath}")

        with open(filepath, 'rb') as f:
            proto_data = pickle.load(f)

        if isinstance(proto_data, torch.Tensor):
            prototypes = proto_data
        else:
            protos = []
            for name in classnames:
                proto = proto_data[name]
                if proto.dim() > 1:
                    proto = proto.mean(dim=0)
                protos.append(proto)
            prototypes = torch.stack(protos, dim=0)

        device = self.backbone.clip_model.visual.conv1.weight.device
        dtype = self.backbone.clip_model.dtype
        return prototypes.to(device=device, dtype=dtype)

    def _configure_optimizer(self):
        for param in self.model.parameters():
            param.requires_grad_(False)

        for param in self.model.shifter.parameters():
            param.requires_grad_(True)

        if self.args.tta_steps > 0:
            self.optimizer = build_optimizer(self.args, self.model.shifter.parameters())
            self.optim_state = self.optimizer.state_dict()
        else:
            self.optimizer = None
            self.optim_state = None

    def _setup_model(self, classnames, arch):
        prototypes = self._load_prototypes(classnames, arch, self.args.test_sets)
        self.model = wrap_prototype_shifter(
            self.backbone,
            prototypes,
            per_label=getattr(self.args, 'per_label', False),
            do_shift=getattr(self.args, 'do_shift', True),
            do_scale=getattr(self.args, 'do_scale', False),
        )
        self.model.eval()
        self.model_state = self.model.shifter.state_dict()
        self._configure_optimizer()

    def reset_classnames(self, classnames, arch):
        self.classnames = classnames
        self._setup_model(classnames, arch)
    
    def test_time_tuning(self, images):
        """
        Test-time tuning on a single batch
        
        Adapts the shift vectors based on the current test batch using:
        1. Confidence-based sample selection (only keep top-p% samples)
        2. Marginal entropy minimization (encourage confident predictions)
        
        Args:
            images: [batch_size, 3, H, W] augmented images
        """
        selected_idx = None
        for _ in range(self.args.tta_steps):
            with torch.amp.autocast(device_type='cuda'):
                output = self.model(images)
                if selected_idx is not None:
                    output = output[selected_idx]
                else:
                    output, selected_idx = select_confident_samples(output, self.args.selection_p)
                loss = marginal_entropy(output)

            self.optimizer.zero_grad()
            self.scaler.scale(loss).backward()
            self.scaler.step(self.optimizer)
            self.scaler.update()
    
    def test_time_adapt_eval(self, val_loader, result_dict=None):
        """
        Test-time adaptation and evaluation
        
        For each test batch:
        1. Reset shift vectors to zero
        2. Perform test-time tuning (if tta_steps > 0)
        3. Evaluate on original image
        4. Record accuracy
        
        Args:
            val_loader: DataLoader for test set
            result_dict: Optional dict to store predictions for ECE calculation
        
        Returns:
            [top1_acc, top5_acc]: List of top-1 and top-5 accuracies
        """
        batch_time = AverageMeter('Time', ':6.3f', Summary.NONE)
        top1 = AverageMeter('Acc@1', ':6.2f', Summary.AVERAGE)
        top5 = AverageMeter('Acc@5', ':6.2f', Summary.AVERAGE)

        progress = ProgressMeter(
            len(val_loader),
            [batch_time, top1, top5],
            prefix='Test: ')

        self.model.eval()

        end = time.time()

        for i, (images, target) in enumerate(val_loader):
            assert self.args.gpu is not None
            if isinstance(images, list):
                for k in range(len(images)):
                    images[k] = images[k].cuda(self.args.gpu, non_blocking=True)
                image = images[0]
                images = torch.cat(images, dim=0)
            else:
                images = images.cuda(self.args.gpu, non_blocking=True)
                image = images
            target = target.cuda(self.args.gpu, non_blocking=True)

            if self.args.tta_steps > 0:
                if self.args.episodic:
                    with torch.no_grad():
                        self.model.reset()
                self.optimizer.load_state_dict(self.optim_state)
                self.test_time_tuning(images)

            with torch.no_grad():
                with torch.amp.autocast(device_type='cuda'):
                    output = self.model(image, test=True)

            # Save results for ECE calculation (if requested)
            if result_dict is not None:
                softmax_output = output.softmax(dim=1)
                max_confidence, max_index = torch.max(softmax_output, 1)

                if max_confidence.numel() == 1:
                    result_dict['max_confidence'].append(max_confidence.item())
                    result_dict['prediction'].append(max_index.item())
                    result_dict['label'].append(target.item())
                else:
                    for j in range(max_confidence.size(0)):
                        result_dict['max_confidence'].append(max_confidence[j].item())
                        result_dict['prediction'].append(max_index[j].item())
                        result_dict['label'].append(target[j].item())

            # Compute accuracy
            acc1, acc5 = accuracy(output, target, topk=(1, 5))
            top1.update(acc1[0], image.size(0))
            top5.update(acc5[0], image.size(0))

            # Measure elapsed time
            batch_time.update(time.time() - end)
            end = time.time()

            if (i+1) % self.args.print_freq == 0:
                progress.display(i)

        progress.display_summary()
        return [top1.avg, top5.avg]